### ISSUE TITLE
Error undefined class 'QPainterPath'

### ISSUE THREAD

**Issue by Kambiz-Asadzadeh** [wang-bin/QtAV#1309]
### Compiler MSVC 2019

Hi, QtAv cannot compile using Qt 5.15.0!
Perhaps the problem is because of changes in **RHI** for latest series of Qt 5!

**Error is in line 75 from FilterContext.h file!**
`QPainterPath clip_path;`

## Errror Log
`error C2079: 'QtAV::VideoFilterContext::clip_path' uses undefined class 'QPainterPath'`
