### ISSUE TITLE
Some problem with PRIVATE_HEADERS

### ISSUE THREAD

**Issue by adauvalter** [wang-bin/QtAV#302]
I'm trying to build last qt version amd faceing the follow problem:

3rd-party\qtav\src\QtAV/private/AVCompat.h(37) : fatal error C1083: Cannot open include file: 'libavformat/avformat.h': No such file or directory

I'm trying to build with new Qt 5.3.2, windows 8.1, VS 2012.
 With 1.3.1 everything works fine. 
Could you please help me?
