### ISSUE TITLE
Question: Does QtAV work well with Qt 6.x? 

### ISSUE THREAD

**Issue by rpw98** [wang-bin/QtAV#1389]
I'm thinking about updating my code from Qt 5.15 to Qt 6.2. But I don't know if QtAV will work with Qt 6.2. Has anyone successfully built QtAV with Qt 6.1/6.2?

Thanks.

**Comment by nicmorais** [comment]
I'm trying to build QtAV on Qt 6.2, but had no success so far.

**Comment by nicmorais** [comment]
So, I've been able to build libQtAV and libQtAVWidgets (separately) under Qt 6.2.2 after several changes, some of them aren't right at all, I know. If you want to try: [nicmorais/QtAV-Qt6](https://github.com/nicmorais/QtAV-Qt6)

**Comment by wang-bin** [comment]
You can try https://github.com/wang-bin/mdk-sdk, it's designed to support any app framework, including qt.

**Comment by MohammadKanan** [comment]
With Qt 6.3 compile fails
I am using QtAV with qml , is it still wip @wang-bin , I am using cmake build , with qt 5.15 QtAV cmake build is possible both with ninja and make builds .. but wuth Qt6.3 both fail .. any clue ? is it possible to know what optional modules of Qt6 are needed other tthan Multimedia ?

**Comment by MohammadKanan** [comment]
I can only build with qt6.2 on Ubuntu / cmake /ninja but 6.3 still fails

**Comment by cgilles** [comment]
My personal feedback : cmake port from qmake is incomplete. Use qmake in all cases.

I'm sure : as QtAV development is stopped since february, i fork the project in digiKam core and review, patch, and improve the implementations. Look the README here for details:

 https://invent.kde.org/graphics/digikam/-/tree/master/core/libs/video/qtav

My cmake port is complete. I also fix plenty of static analyzer reports. My code compile under Qt6, but i drop QML as i don't need for digiKam.

Best

Gilles Caulier

**Comment by MohammadKanan** [comment]
@cgilles thanks for caring , it seems I had wrong specifying QTDIR , I now can build with q6 6.0.0 from QtCreator or command line both ninja and make , I just disabled tests , not sure if related

**Comment by MohammadKanan** [comment]
@cgilles  Yes , seems to be the case .. CMakeLists still finding Qt5 modules

**Comment by cgilles** [comment]
Note: my port to Qt6 is complete. QtAV original code port to Qt6 was partial. Look weel the README, i explain well all tasks done over QtAV source code.

**Comment by MohammadKanan** [comment]
Qt 6.2.4 / qmake failes this error
filter/X11FilterContext.cpp:185: error: ‘class QFontMetrics’ has no member named ‘width’
QtAV/src/filter/X11FilterContext.cpp: In member function ‘virtual void QtAV::X11FilterContext::drawPlainText(const QPointF&, const QString&)’:

**Comment by cgilles** [comment]
I already fixed the problem:

https://invent.kde.org/graphics/digikam/-/blob/master/core/libs/video/qtav/src/filter/X11FilterContext.cpp#L236

Gilles Caulier

**Comment by MohammadKanan** [comment]
@cgilles , thank you unfortunately my primary interest is the QML port , you say its not included in your fix ?

**Comment by cgilles** [comment]
yes, with digiKam , we don't use QML code in favor of C++, for speed reasons, and to be homogeneous, as digiKam is more than 1.5 M C++ code lines.

But you can backport my fixes in a personal QtAV port including original QML code, with your fixes for these implementations.

Gilles Caulier
