### ISSUE TITLE
Problem with pixelFormat property

### ISSUE THREAD

**Issue by PSlash** [wang-bin/QtAV#436]
Not able to build on Mac Qt5.4:
Undefined symbols for architecture x86_64:
  "QtAV::VideoEncoder::setPixelFormat(QtAV::VideoFormat::PixelFormat)", referenced from:
      QtAV::VideoEncoder::qt_metacall(QMetaObject::Call, int, void**) in moc_VideoEncoder.o
  "QtAV::VideoEncoder::pixelFormat() const", referenced from:
      QtAV::AVMuxer::Private::addStream(AVFormatContext*, AVCodecID) in AVMuxer.o
      QtAV::VideoEncoder::qt_metacall(QMetaObject::Call, int, void**) in moc_VideoEncoder.o
ld: symbol(s) not found for architecture x86_64

Functions 
    void setPixelFormat(const VideoFormat::PixelFormat format);
    VideoFormat::PixelFormat pixelFormat() const;
are defined at VideoEncoder.h but there is no implementation of them.

**Comment by dkomer** [comment]
Interesting... this is my first time trying to build QtAV, or any Qt project for that matter, and I ran into the same error on windows, using latest ffmpeg stuff from sourceforge windows depends. Bad timing? :)

**Comment by wang-bin** [comment]
sorry, i forgot to commit a file. fixed now

**Comment by PSlash** [comment]
Sorry, but I'm can't confirm. Build fails:
---
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names '-Wl,-rpath,/Users/Slava/Projects/Libraries/!builds/QtAV-latest/Release/lib_mac_x86_64_llvm' '-Wl,-rpath,@loader_path/../Frameworks' '-Wl,-rpath,@executable_path/../Frameworks' -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/Slava/Qt/official/5.4/clang_64/lib -o ../../bin/extract ../../.obj/extract_mac_x86_64_llvm/main.o   -F/Users/Slava/Qt/official/5.4/clang_64/lib -L/usr/local/ffmpeg/2.6.2/lib/ -L/usr/local/lib -F/Users/Slava/Projects/Libraries/!builds/QtAV-latest/Release/lib_mac_x86_64_llvm -framework QtAV -framework OpenAL -framework VideoDecodeAcceleration -framework CoreVideo -framework CoreFoundation -framework IOSurface -L/Users/Slava/Qt/official/5.4/clang_64/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL -framework QtAVWidgets -lavformat -lavcodec -lswscale -lavutil -lm -lpthread -lfaac -ltheora -ltheoraenc -ltheoradec -logg -lvorbis -lvorbisenc -lvorbisfile -lmp3lame -lx264 -lopencore-amrnb -lopencore-amrwb -lvpx -lxvidcore -lpostproc -lswresample -lavfilter -liconv -lbz2 -lz -framework QtOpenGL -framework QtWidgets 
22:55:57: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project QtAV (kit: Desktop Qt 5.4.1 clang 64bit)
When executing step "Make"
22:55:57: Elapsed time: 00:27.
----
But I'm able to build '2b983111211afe8facc8a3d9737e14a4caf76428'

**Comment by wang-bin** [comment]
@PSlash No more details about the error?

**Comment by dkomer** [comment]
I was able to build the project now... however, after running sdk_install and trying to get my first test player going, I get this error: LINK : fatal error LNK1104: cannot open file 'C:\Qt\Qt5.4.1\5.4\msvc2013_64\lib\Qt5AVWidgetsd.lib'

Not sure if it's related to this or a separate issue or just my newbie mistake :)

Here's my test code:

```
#include <QApplication>
#include <QDesktopWidget>
#include <QStyle>

#include <QtAV/QtAV.h>
#include <QtAV>
#include <QtAVWidgets>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
	QtAV::GLWidgetRenderer2 renderer;
	
	QtAV::Widgets::registerRenderers();
	
	renderer.show();
	
	QtAV::AVPlayer player;
	player.setRenderer(&renderer);
	player.play("test.avi");
	
    return app.exec();
}

```

**Comment by PSlash** [comment]
There i no additional info. make quits unexpectedly without error message.
I've done following: reseted master branch to '4c2716b53b742e9b0938a01e5f2d10c0cb9f508c' and cherry-pick 'a3e75e849016c7b033e94640e2e0701b25fdc9ad'.
In this case library builds fine. Thus,  this issue could be closed.
