### ISSUE TITLE
Error build on MSVC2017 and Qt5.12.3 

### ISSUE THREAD

**Issue by xiaosumay** [wang-bin/QtAV#1250]
### QtAV master , Qt 5.12.3, vs2017

编译出错 **SurfaceInteropD3D9.obj : error LNK2019: unresolved external symbol "enum QtAV::VideoFormat::PixelFormat __cdecl QtAV::pixelFormatFromFourcc(int)"**
```
C:\qt\build\QtAV-Desktop_Qt_5_12_3_MSVC2017_64bit-Profile\src>C:/Qt/Qt5.12.3/Tools/QtCreator/bin/jom.exe  
	C:\Qt\Qt5.12.3\Tools\QtCreator\bin\jom.exe -f Makefile.Release
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /SAFESEH:NO /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcmtd.lib /DEBUG /OPT:REF /INCREMENTAL:NO /DLL /SUBSYSTEM:WINDOWS /VERSION:1.13 /MANIFEST:embed /OUT:..\out\lib_win_\QtAV1.dll @C:\Users\ray\AppData\Local\Temp\QtAV1.dll.1072.297.jom
   Creating library ..\out\lib_win_\QtAV1.lib and object ..\out\lib_win_\QtAV1.exp
SurfaceInteropD3D9.obj : error LNK2019: unresolved external symbol "enum QtAV::VideoFormat::PixelFormat __cdecl QtAV::pixelFormatFromFourcc(int)" (?pixelFormatFromFourcc@QtAV@@YA?AW4PixelFormat@VideoFormat@1@H@Z) referenced in function "protected: void * __cdecl QtAV::d3d9::SurfaceInterop::mapToHost(class QtAV::VideoFormat const &,void *,int)" (?mapToHost@SurfaceInterop@d3d9@QtAV@@IEAAPEAXAEBVVideoFormat@3@PEAXH@Z)
..\out\lib_win_\QtAV1.dll : fatal error LNK1120: 1 unresolved externals
jom: C:\qt\build\QtAV-Desktop_Qt_5_12_3_MSVC2017_64bit-Profile\src\Makefile.Release [..\out\lib_win_\QtAV1.dll] Error 1120
jom: C:\qt\build\QtAV-Desktop_Qt_5_12_3_MSVC2017_64bit-Profile\src\Makefile [release] Error 2
10:49:40: 进程"C:\Users\ray\msvc_make.bat"退出，退出代码 2 。
Error while building/deploying project QtAV (kit: Desktop Qt 5.12.3 MSVC2017 64bit)
```

**Comment by xiaosumay** [comment]
原因是项目没有生成 `VideoDecoderD3D11.cpp` 的`obj` 
![image](https://user-images.githubusercontent.com/9405101/66974631-47cc2080-f0ce-11e9-99e7-c6140892626f.png)

**Comment by UnknownObject000** [comment]
My envorment is MSVC2017 and Qt5.12.3 too.The release of is seems support VS2015,but what should I do?I'll try to bulid it and report the errors here.

**Comment by UnknownObject000** [comment]
When I bulid it,there are many error LNK2019,such as:"AudioResamplerFF.obj:-1: error: LNK2019: 无法解析的外部符号 _swr_init，该符号在函数 "public: virtual bool __thiscall QtAV::AudioResamplerFF::prepare(void)" (?prepare@AudioResamplerFF@QtAV@@UAE_NXZ) 中被引用"
I have already copied lib file into my Qt install path.What should I do?

**Comment by xiaosumay** [comment]
听说这个项目已经不维护~

**Comment by UnknownObject000** [comment]
停止维护？？

**Comment by lanbudao** [comment]
> 听说这个项目已经不维护~

请问这个问题你们解决没有？

**Comment by GrammerT** [comment]
add  CONFIG *= d3dva to libQtAV.pro in win32:!winrt section .

**Comment by dm-helper** [comment]
Thanks, this really seems to have fixed the issue. I had to disable the config tests which was not able to autodetect avutil. Do you have any tips about that?

**Comment by AWeiLuping** [comment]
请问这个问题你们解决没有？

**Comment by AWeiLuping** [comment]
请问这个问题你们解决没有？我也遇到相同的问题。
