### ISSUE TITLE
Build with MXE on Ubuntu 14.04

### ISSUE THREAD

**Issue by tom4tom** [wang-bin/QtAV#585]
Hi,
try to build with MXE i686-w64-mingw32.static from Ubuntu Repo.
Using : QtAV-depends-windows-x86+x64
Try to make with an without CONFIG += static_ffmpeg

Running into Linker Errors like:
./../.obj/QtAV_win_x86/qrc_shaders.o:qrc_shaders.cpp:(.text+0x54): undefined reference to `_imp___Z21qRegisterResourceDataiPKhS0_S0_'
./../.obj/QtAV_win_x86/qrc_shaders.o:qrc_shaders.cpp:(.text+0x94): undefined reference to `_imp___Z23qUnregisterResourceDataiPKhS0_S0_'
./../.obj/QtAV_win_x86/qrc_shaders.o:qrc_shaders.cpp:(.text.startup+0x24): undefined reference to `_imp___Z21qRegisterResourceDataiPKhS0_S0_'
collect2: error: ld returned 1 exit status
make[2]: *** [../lib_win_x86/QtAV1.dll] Fehler 1
make[2]: Verzeichnis »/home/tmaier/QtProjekte/QtAV/src« wird verlassen
make[1]: *** [release] Fehler 2
make[1]: Verzeichnis »/home/tmaier/QtProjekte/QtAV/src« wird verlassen
make: *** [sub-src-libQtAV-pro-make_default] Fehler 2

Any help?

ToM

**Comment by wang-bin** [comment]
How to build with MXE?

**Comment by tom4tom** [comment]
Installed MXE from Ubuntu 14.04 Repo
1. Try with MXW FFMPEG 2. with QtAV-depends-windows-x86+x64
git clone https://github.com/wang-bin/QtAV.git
git submodule update --init
delete .qmake.cache
/usr/lib/mxe/usr/i686-w64-mingw32.static/qt/bin/qmake 'CONFIG+=recheck'
/usr/lib/mxe/usr/i686-w64-mingw32.static/qt/bin/qmake
make
It ends up with the Errors above....

.qmake.cache:
QTAV_MAJOR_VERSION = 1
QTAV_MINOR_VERSION = 9
QTAV_PATCH_VERSION = 0
QTAV_VERSION = 1.9.0
TARGET_ARCH = x86
TARGET_ARCH_SUB =
CONFIG += static_ffmpeg
CONFIG += x86
CONFIG +=
QT_BIN = /usr/lib/mxe/usr/i686-w64-mingw32.static/qt/bin
BUILD_DIR = /home/tmaier/QtProjekte/QtAV
SOURCE_ROOT = /home/tmaier/QtProjekte/QtAV
mkspecs_cached = /usr/lib/mxe/usr/i686-w64-mingw32.static/qt/mkspecs
CONFIG -= mac_dylib
CONFIG -= no_widgets
CONFIG += config_avutil
CONFIG += done_config_avutil
CONFIG += config_avcodec
CONFIG += done_config_avcodec
CONFIG += config_avformat
CONFIG += done_config_avformat
CONFIG += config_swscale
CONFIG += done_config_swscale
CONFIG += config_swresample
CONFIG += done_config_swresample
CONFIG += done_config_avresample
CONFIG += config_avfilter
CONFIG += done_config_avfilter
CONFIG += config_avdevice
CONFIG += done_config_avdevice
CONFIG += config_gl
CONFIG += done_config_gl
CONFIG += config_sse4_1
CONFIG += done_config_sse4_1
CONFIG += config_openal
CONFIG += done_config_openal
CONFIG += config_libass
CONFIG += done_config_libass
CONFIG += done_config_uchardet
CONFIG += done_config_xaudio2
CONFIG += config_direct2d
CONFIG += done_config_direct2d
CONFIG += config_dxva
CONFIG += done_config_dxva
CONFIG += config_dsound
CONFIG += done_config_dsound
CONFIG += done_config_gdiplus

**Comment by wang-bin** [comment]
Sorry, I have no idea. I can build QtAV on ubuntu 15.10 with x86_64-w64-mingw32. btw, what does `static` mean in `i686-w64-mingw32.static`?

**Comment by tom4tom** [comment]
Ah sorry, I forget to say: I use this Repo: http://pkg.mxe.cc/
http://pkg.mxe.cc/repos/apt/debian
And changed this in libQtAV.pro
## TODO: build xaudio2 code as a seperate static lib so wen can safely add contrib/dxsdk to INCLUDEPATH for that lib build
**##**    win32-icc|win32-g++|win32-msvc2010|win32-msvc2008|win32-msvc2005: \

Do you use x86_64-w64-mingw32 from 15.10 reop?

**Comment by wang-bin** [comment]
I use x86_64-w64-mingw32 on ubuntu 15.10 to test cross build for windows.

**Comment by tom4tom** [comment]
Ah, MXE x86_64-w64-mingw32.shared make the Build ;-)
But a lot of *.dll are missing (QtCore4.dll, libwinpthread-1.dll .......)

**Comment by wang-bin** [comment]
mxe qt5 build is fine
