### ISSUE TITLE
Error when build on Qt 5.7 msvc2015 x86

### ISSUE THREAD

**Issue by anhlt309** [wang-bin/QtAV#675]
Hi wang,
I found error when compiling:
Creating library ..\lib_win_x86\QtAV1.lib and object ..\lib_win_x86\QtAV1.exp
SurfaceInteropD3D9.obj : error LNK2019: unresolved external symbol "enum QtAV::VideoFormat::PixelFormat __cdecl QtAV::pixelFormatFromFourcc(int)" (?pixelFormatFromFourcc@QtAV@@YA?AW4PixelFormat@VideoFormat@1@H@Z) referenced in function "protected: void * __thiscall QtAV::d3d9::SurfaceInterop::mapToHost(class QtAV::VideoFormat const &,void *,int)" (?mapToHost@SurfaceInterop@d3d9@QtAV@@IAEPAXABVVideoFormat@3@PAXH@Z)

Does I miss add some libs or macro?

**Comment by wang-bin** [comment]
Did you read wiki? It never happens if you follow the wiki.
