### ISSUE TITLE
It just work with libav version 0.8 not above

### ISSUE THREAD

**Issue by jmimi** [wang-bin/QtAV#130]
When compiling QtAV with libav version above 0.8, I encountered below exception :
‘CODEC_ID_MPEG1VIDEO’ was not declared in this scope
I checked libav source code and found libav changed "CODEC_ID_MPEG1VIDEO" to "AV_CODEC_ID_MPEG1VIDEO" in versions above 0.8
