### ISSUE TITLE
ffmpeg 4.0 support

### ISSUE THREAD

**Issue by kelteseth** [wang-bin/QtAV#1073]
### QtAV, Qt version and platform
QtAV git 98f58545d7, Qt 5.10.1, Windows 10 MSYS2

### Compiler Error
Compling via  git 98f58545d7
```
QtAV\private\AVCompat.h:79: error: libavresample/avresample.h: No such file or directory
 #include <libavresample/avresample.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

When Changing;
```
config_avresample {
    DEFINES += QTAV_HAVE_AVRESAMPLE=1 -> to 0
    SOURCES += AudioResamplerLibav.cpp
    LIBS += -lavresample
}
```
I get this error:
```
QtAV\src\AudioResamplerTemplate.cpp:235: error: 'avresample_set_matrix' was not declared in this scope
         avresample_set_matrix(d.context, matrix, in_c);
         ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by kelteseth** [comment]
So it works now via commenting:
```
 #LIBS += -lavresample
```
and
```
#if QTAV_HAVE(SWR_AVR_MAP) //LIBAVRESAMPLE_VERSION_INT < AV_VERSION_INT(1, 1, 0) -> to false
```

**Comment by cgilles** [comment]
Same problem here under MacOS with Macports, which has just updated ffmpeg to last 4.0, and now QtAv do not compile as expected. We need a solution quickly. A next QtAV 1.13.0 will be great to fix this problem...

**Comment by wang-bin** [comment]
@cgilles what's the error? I can build with 4.0 without error.

**Comment by cgilles** [comment]
Confirmed. QtAV master code compile fine with ffmpeg 4 under MAcOS/macports.

But you have plenty of warnings to fix about deprecated ffmpeg methods.

https://drive.google.com/open?id=1yGMpcnUvQXX9PpH6ukcKeQMb3jrkdkws
Note : i use QtAV in my office (French scientific research center) where your code is parsed by clang static analyzer automatically with Jenkins, and i see a lots of warnings to fix. Please run scan-build tool over your code and enjoy.

**Comment by cgilles** [comment]
Note : under Linux with ffmpeg 3.3.6 , code from master do not compiled until end, through scan-build : 
/usr/bin/../libexec/c++-analyzer -c -pipe -std=gnu++0x -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fno-strict-aliasing -DPIC -fPIC -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DBUILD_QTAVWIDGETS_LIB -DQTAV_HAVE_GL=1 -DQTAV_HAVE_XV=1 -DQTAV_HAVE_X11=1 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/mnt/devel/GIT/QtAV/widgets -I. -I/usr/lib64/qt5/include -I/mnt/devel/GIT/QtAV/src -I/mnt/devel/GIT/QtAV -I/mnt/devel/GIT/QtAV/src/QtAV -I/mnt/devel/GIT/QtAV/widgets -I/mnt/devel/GIT/QtAV -I/mnt/devel/GIT/QtAV/widgets/QtAVWidgets -I/usr/lib64/qt5/include/QtOpenGL -I/usr/lib64/qt5/include/QtWidgets -I/usr/lib64/qt5/include/QtGui -I/usr/lib64/qt5/include/QtCore -I../.moc/5.6.2/QtAVWidgets -I/usr/lib64/qt5/mkspecs/linux-g++ -o ../.obj/QtAVWidgets_linux_x86_64/GraphicsItemRenderer.o /mnt/devel/GIT/QtAV/widgets/GraphicsItemRenderer.cpp
In file included from /mnt/devel/GIT/QtAV/src/QtAV/private/QPainterRenderer_p.h:28:0,
                 from /mnt/devel/GIT/QtAV/widgets/GraphicsItemRenderer.cpp:23:
/mnt/devel/GIT/QtAV/src/QtAV/private/VideoRenderer_p.h: Dans la fonction membre ‘bool QtAV::VideoRendererPrivate::computeOutParameters(qreal)’:
/mnt/devel/GIT/QtAV/src/QtAV/private/VideoRenderer_p.h:84:50: erreur : ‘class QtAV::Statistics::VideoOnly’ has no member named ‘rotate’
             rotate += int(statistics->video_only.rotate);
                                                  ^
/mnt/devel/GIT/QtAV/src/QtAV/private/VideoRenderer_p.h: Dans la fonction membre ‘int QtAV::VideoRendererPrivate::rotation() const’:
/mnt/devel/GIT/QtAV/src/QtAV/private/VideoRenderer_p.h:107:39: erreur : ‘class QtAV::Statistics::VideoOnly’ has no member named ‘rotate’
         return statistics->video_only.rotate + orientation;
                                       ^
Makefile.libQtAVWidgets:1967 : la recette pour la cible « ../.obj/QtAVWidgets_linux_x86_64/GraphicsItemRenderer.o » a échouée

anyway, i can share for you the first errors detected by Clang static analyzer until this error : 

https://drive.google.com/open?id=15riPjjr-atFJoYfZaso72_O5grPTjV4a

Gilles Caulier

**Comment by cgilles** [comment]
Ok, i reconfigured all under Linux and now all compile fine as expected.

I updated the clang static analyzer trace here : 

https://drive.google.com/open?id=15riPjjr-atFJoYfZaso72_O5grPTjV4a

Gilles Caulier

**Comment by cgilles** [comment]
See also the HTML report of cppcheck static analyzer running against git/master code : 

https://drive.google.com/open?id=1YXONToJTmXjynBmnMfVzA5edHpI5I1iC

Gilles Caulier

**Comment by cgilles** [comment]
And the last one : Krazy static analyzer report. It's used by KDE project, and i fix a lots of cosmetic Qt coding style in digiKam project (more than 2M lines of code)

https://drive.google.com/open?id=1qrlht9H4R7u1dsEyDfYZYi6fkpiBdIOg

Have fun

Gilles Caulier
